#!/usr/bin/env tsx
import { insertMunicipalities } from './discover-province';

const municipalities = [
  {"name":"Montréal","province":"Quebec","country":"Canada","municipality_type":"Ville","population":1992510,"official_website":"https://montreal.ca","minutes_url":"https://montreal.ca/conseils-decisionnels/conseil-municipal","scan_status":"pending"},
  {"name":"Québec","province":"Quebec","country":"Canada","municipality_type":"Ville","population":605194,"official_website":"https://www.ville.quebec.qc.ca","minutes_url":"https://www.ville.quebec.qc.ca/apropos/gouvernance/conseil-municipal/proces_verbaux.aspx","scan_status":"pending"},
  {"name":"Laval","province":"Quebec","country":"Canada","municipality_type":"Ville","population":468670,"official_website":"https://www.laval.ca","minutes_url":"https://www.laval.ca/en/democratic-life/town-hall-elected-officials/executive-summaries-agendas-minutes/","scan_status":"pending"},
  {"name":"Gatineau","province":"Quebec","country":"Canada","municipality_type":"Ville","population":311538,"official_website":"https://www.gatineau.ca","minutes_url":"https://www.gatineau.ca/portail/default.aspx?p=publications_cartes_statistiques_donnees_ouvertes/proces_verbaux","scan_status":"pending"},
  {"name":"Longueuil","province":"Quebec","country":"Canada","municipality_type":"Ville","population":274650,"official_website":"https://longueuil.quebec","minutes_url":"https://www.longueuil.quebec/fr/services/instances-decisionnelles-et-consultatives/proces-verbaux","scan_status":"pending"},
  {"name":"Sherbrooke","province":"Quebec","country":"Canada","municipality_type":"Ville","population":189131,"official_website":"https://www.sherbrooke.ca","minutes_url":"https://www.sherbrooke.ca/fr/vie-municipale/publications/proces-verbaux","scan_status":"pending"},
  {"name":"Lévis","province":"Quebec","country":"Canada","municipality_type":"Ville","population":162922,"official_website":"https://www.ville.levis.qc.ca","minutes_url":"https://www.ville.levis.qc.ca/la-ville/conseil-municipal/proces-verbaux/","scan_status":"pending"},
  {"name":"Saguenay","province":"Quebec","country":"Canada","municipality_type":"Ville","population":153495,"official_website":"https://ville.saguenay.ca","minutes_url":"https://ville.saguenay.ca/la-ville-et-vie-democratique/publications/proces-verbaux","scan_status":"pending"},
  {"name":"Trois-Rivières","province":"Quebec","country":"Canada","municipality_type":"Ville","population":152253,"official_website":"https://www.v3r.net","minutes_url":"https://www.v3r.net/a-propos-de-la-ville/vie-democratique/ordres-du-jour-et-proces-verbaux","scan_status":"pending"},
  {"name":"Terrebonne","province":"Quebec","country":"Canada","municipality_type":"Ville","population":128203,"official_website":"https://terrebonne.ca","minutes_url":"https://terrebonne.ca/seances-du-conseil-municipal/","scan_status":"pending"},
  {"name":"Saint-Jean-sur-Richelieu","province":"Quebec","country":"Canada","municipality_type":"Ville","population":101759,"official_website":"https://sjsr.ca","minutes_url":"https://sjsr.ca/seances-du-conseil/","scan_status":"pending"},
  {"name":"Brossard","province":"Quebec","country":"Canada","municipality_type":"Ville","population":100322,"official_website":"https://brossard.ca","minutes_url":"https://www.brossard.ca/vie-municipale/conseil-municipal/assemblees-du-conseil","scan_status":"pending"},
  {"name":"Repentigny","province":"Quebec","country":"Canada","municipality_type":"Ville","population":91149,"official_website":"https://repentigny.ca","minutes_url":"https://www.ville.repentigny.qc.ca/vie-democratique/seances-du-conseil.html","scan_status":"pending"},
  {"name":"Drummondville","province":"Quebec","country":"Canada","municipality_type":"Ville","population":86983,"official_website":"https://www.drummondville.ca","minutes_url":"https://www.drummondville.ca/mairie-et-vie-municipale/seances-du-conseil/","scan_status":"pending"},
  {"name":"Saint-Jérôme","province":"Quebec","country":"Canada","municipality_type":"Ville","population":86908,"official_website":"https://www.vsj.ca","minutes_url":"https://www.vsj.ca/conseil-municipal-et-comite-executif/proces-verbaux/","scan_status":"pending"},
  {"name":"Granby","province":"Quebec","country":"Canada","municipality_type":"Ville","population":73065,"official_website":"https://www.granby.ca","minutes_url":"https://www.granby.ca/fr/ville/seances-du-conseil-municipal-2026","scan_status":"pending"},
  {"name":"Mirabel","province":"Quebec","country":"Canada","municipality_type":"Ville","population":71572,"official_website":"https://mirabel.ca","minutes_url":"https://mirabel.ca/ville/vie-democratique/seances-du-conseil","scan_status":"pending"},
  {"name":"Blainville","province":"Quebec","country":"Canada","municipality_type":"Ville","population":62709,"official_website":"https://blainville.ca","minutes_url":"https://blainville.ca/ville/portrait-de-blainville/proces-verbaux-des-seances-du-conseil","scan_status":"pending"},
  {"name":"Saint-Hyacinthe","province":"Quebec","country":"Canada","municipality_type":"Ville","population":61814,"official_website":"https://www.st-hyacinthe.ca","minutes_url":"https://www.st-hyacinthe.ca/ville/vie-democratique/seances-publiques","scan_status":"pending"},
  {"name":"Mascouche","province":"Quebec","country":"Canada","municipality_type":"Ville","population":58172,"official_website":"https://mascouche.ca","minutes_url":"https://mascouche.ca/mairie/seances-du-conseil/","scan_status":"pending"},
  {"name":"Châteauguay","province":"Quebec","country":"Canada","municipality_type":"Ville","population":54378,"official_website":"https://ville.chateauguay.qc.ca","minutes_url":"https://ville.chateauguay.qc.ca/affaires-municipales/conseil-municipal/","scan_status":"pending"},
  {"name":"Rimouski","province":"Quebec","country":"Canada","municipality_type":"Ville","population":52443,"official_website":"https://rimouski.ca","minutes_url":"https://rimouski.ca/ville/democratie/proces-verbaux","scan_status":"pending"},
  {"name":"Shawinigan","province":"Quebec","country":"Canada","municipality_type":"Ville","population":52179,"official_website":"https://www.shawinigan.ca","minutes_url":"https://www.shawinigan.ca/ville/conseil-municipal/seances-du-conseil/","scan_status":"pending"},
  {"name":"Dollard-des-Ormeaux","province":"Quebec","country":"Canada","municipality_type":"Ville","population":50845,"official_website":"https://ville.ddo.qc.ca","minutes_url":"https://ville.ddo.qc.ca/en/my-city/council/council-meetings/","scan_status":"pending"},
  {"name":"Victoriaville","province":"Quebec","country":"Canada","municipality_type":"Ville","population":50579,"official_website":"https://www.victoriaville.ca","minutes_url":"https://www.victoriaville.ca/documents/?ID=1","scan_status":"pending"},
  {"name":"Saint-Eustache","province":"Quebec","country":"Canada","municipality_type":"Ville","population":47973,"official_website":"https://www.saint-eustache.ca","minutes_url":"https://www.saint-eustache.ca/mairie-conseil-municipal/seances-du-conseil","scan_status":"pending"},
  {"name":"Vaudreuil-Dorion","province":"Quebec","country":"Canada","municipality_type":"Ville","population":47909,"official_website":"https://www.ville.vaudreuil-dorion.qc.ca","minutes_url":"https://www.ville.vaudreuil-dorion.qc.ca/fr/la-ville/mairie/seances-publiques","scan_status":"pending"},
  {"name":"Salaberry-de-Valleyfield","province":"Quebec","country":"Canada","municipality_type":"Ville","population":47310,"official_website":"https://www.ville.valleyfield.qc.ca","minutes_url":"http://www.ville.valleyfield.qc.ca/proces-verbaux-conseil-municipal","scan_status":"pending"},
  {"name":"Rouyn-Noranda","province":"Quebec","country":"Canada","municipality_type":"Ville","population":43564,"official_website":"https://www.rouyn-noranda.ca","minutes_url":"http://www.ville.rouyn-noranda.qc.ca/fr/page/proces-verbaux-et-ordres-du-jour/","scan_status":"pending"},
  {"name":"Boucherville","province":"Quebec","country":"Canada","municipality_type":"Ville","population":42066,"official_website":"https://www.boucherville.ca","minutes_url":"https://www.boucherville.ca/mairie-conseil/seances-du-conseil/","scan_status":"pending"}
];

insertMunicipalities(municipalities);
