#!/usr/bin/env tsx
import { insertMunicipalities } from './discover-province';

const municipalities = [
  {"name":"Vancouver","province":"British Columbia","country":"Canada","municipality_type":"City","population":776584,"official_website":"https://vancouver.ca","minutes_url":"https://covapp.vancouver.ca/councilMeetingPublic/CouncilMeetings.aspx","scan_status":"pending"},
  {"name":"Surrey","province":"British Columbia","country":"Canada","municipality_type":"City","population":736057,"official_website":"https://www.surrey.ca","minutes_url":"https://www.surrey.ca/city-government/council-meetings/council-committee-commission-board-and-task-force-minutes","scan_status":"pending"},
  {"name":"Burnaby","province":"British Columbia","country":"Canada","municipality_type":"City","population":310666,"official_website":"https://www.burnaby.ca","minutes_url":"https://pub-burnaby.escribemeetings.com","scan_status":"pending"},
  {"name":"Richmond","province":"British Columbia","country":"Canada","municipality_type":"City","population":250915,"official_website":"https://www.richmond.ca","minutes_url":"https://citycouncil.richmond.ca/agendas.htm","scan_status":"pending"},
  {"name":"Abbotsford","province":"British Columbia","country":"Canada","municipality_type":"City","population":181726,"official_website":"https://www.abbotsford.ca","minutes_url":"https://www.abbotsford.ca/city-hall/council-committee-meetings/agendas-minutes-and-videos","scan_status":"pending"},
  {"name":"Coquitlam","province":"British Columbia","country":"Canada","municipality_type":"City","population":180845,"official_website":"https://www.coquitlam.ca","minutes_url":"https://www.coquitlam.ca/agendacenter","scan_status":"pending"},
  {"name":"Kelowna","province":"British Columbia","country":"Canada","municipality_type":"City","population":172960,"official_website":"https://www.kelowna.ca","minutes_url":"https://kelownapublishing.escribemeetings.com","scan_status":"pending"},
  {"name":"Township of Langley","province":"British Columbia","country":"Canada","municipality_type":"Township","population":171566,"official_website":"https://www.tol.ca","minutes_url":"https://www.tol.ca/en/the-township/council-agendas-and-minutes.aspx","scan_status":"pending"},
  {"name":"Delta","province":"British Columbia","country":"Canada","municipality_type":"District","population":129193,"official_website":"https://www.delta.ca","minutes_url":"https://pub-delta.escribemeetings.com","scan_status":"pending"},
  {"name":"Saanich","province":"British Columbia","country":"Canada","municipality_type":"District","population":127310,"official_website":"https://www.saanich.ca","minutes_url":"https://www.saanich.ca/EN/main/local-government/mayor-council/schedule-agendas-minutes.html","scan_status":"pending"},
  {"name":"Nanaimo","province":"British Columbia","country":"Canada","municipality_type":"City","population":114830,"official_website":"https://www.nanaimo.ca","minutes_url":"https://www.nanaimo.ca/your-government/city-council/council-meetings/meeting-documents-and-videos","scan_status":"pending"},
  {"name":"Kamloops","province":"British Columbia","country":"Canada","municipality_type":"City","population":113365,"official_website":"https://www.kamloops.ca","minutes_url":"https://kamloops.civicweb.net/Portal/MeetingSchedule.aspx","scan_status":"pending"},
  {"name":"Maple Ridge","province":"British Columbia","country":"Canada","municipality_type":"District","population":111457,"official_website":"https://www.mapleridge.ca","minutes_url":"https://www.mapleridge.ca/811/Council-Agendas-Minutes","scan_status":"pending"},
  {"name":"Victoria","province":"British Columbia","country":"Canada","municipality_type":"City","population":106112,"official_website":"https://www.victoria.ca","minutes_url":"https://pub-victoria.escribemeetings.com","scan_status":"pending"},
  {"name":"Chilliwack","province":"British Columbia","country":"Canada","municipality_type":"City","population":106103,"official_website":"https://www.chilliwack.com","minutes_url":"https://www.chilliwack.com/main/page.cfm?id=3059","scan_status":"pending"},
  {"name":"District of North Vancouver","province":"British Columbia","country":"Canada","municipality_type":"District","population":101303,"official_website":"https://www.dnv.org","minutes_url":"https://www.dnv.org/government-administration/meeting-agendas-and-minutes","scan_status":"pending"},
  {"name":"New Westminster","province":"British Columbia","country":"Canada","municipality_type":"City","population":96580,"official_website":"https://www.newwestcity.ca","minutes_url":"https://www.newwestcity.ca/city_hall/council_agendas_meetings/council-meeting-agendas-reports-minutes","scan_status":"pending"},
  {"name":"Prince George","province":"British Columbia","country":"Canada","municipality_type":"City","population":86712,"official_website":"https://www.princegeorge.ca","minutes_url":"https://www.princegeorge.ca/city-hall/mayor-council/meetings-agendas-minutes","scan_status":"pending"},
  {"name":"Port Coquitlam","province":"British Columbia","country":"Canada","municipality_type":"City","population":71292,"official_website":"https://www.portcoquitlam.ca","minutes_url":"https://pub-portcoquitlam.escribemeetings.com","scan_status":"pending"},
  {"name":"City of North Vancouver","province":"British Columbia","country":"Canada","municipality_type":"City","population":70152,"official_website":"https://www.cnv.org","minutes_url":"https://www.cnv.org/City-Hall/Council-Meetings/Council-Agendas,-Minutes-and-Videos","scan_status":"pending"},
  {"name":"Langford","province":"British Columbia","country":"Canada","municipality_type":"City","population":63120,"official_website":"https://langford.ca","minutes_url":"https://langford.ca/city-hall/agendas-and-minutes","scan_status":"pending"},
  {"name":"Vernon","province":"British Columbia","country":"Canada","municipality_type":"City","population":50955,"official_website":"https://www.vernon.ca","minutes_url":"https://www.vernon.ca/government-services/mayor-council/council-meetings/council-meeting-agenda-minutes","scan_status":"pending"},
  {"name":"West Vancouver","province":"British Columbia","country":"Canada","municipality_type":"District","population":49896,"official_website":"https://westvancouver.ca","minutes_url":"https://westvancouver.ca/mayor-council/council-agendas-minutes","scan_status":"pending"},
  {"name":"Mission","province":"British Columbia","country":"Canada","municipality_type":"District","population":47765,"official_website":"https://www.mission.ca","minutes_url":"https://www.mission.ca/council-government/meetings-agendas","scan_status":"pending"},
  {"name":"West Kelowna","province":"British Columbia","country":"Canada","municipality_type":"City","population":41556,"official_website":"https://www.westkelownacity.ca","minutes_url":"https://calendar.westkelownacity.ca/councilcommittee","scan_status":"pending"},
  {"name":"Port Moody","province":"British Columbia","country":"Canada","municipality_type":"City","population":39689,"official_website":"https://www.portmoody.ca","minutes_url":"https://calendar.portmoody.ca/meetings","scan_status":"pending"},
  {"name":"Penticton","province":"British Columbia","country":"Canada","municipality_type":"City","population":39655,"official_website":"https://www.penticton.ca","minutes_url":"https://www.penticton.ca/city-hall/city-council/council-meetings/agendas-minutes","scan_status":"pending"},
  {"name":"Campbell River","province":"British Columbia","country":"Canada","municipality_type":"City","population":39033,"official_website":"https://www.campbellriver.ca","minutes_url":"https://www.campbellriver.ca/your-city-hall/city-council/agendas-minutes-schedule-webcasts/agendas-and-minutes","scan_status":"pending"},
  {"name":"City of Langley","province":"British Columbia","country":"Canada","municipality_type":"City","population":37048,"official_website":"https://www.langleycity.ca","minutes_url":"https://pub-langleycity.escribemeetings.com","scan_status":"pending"},
  {"name":"North Cowichan","province":"British Columbia","country":"Canada","municipality_type":"District","population":35436,"official_website":"https://www.northcowichan.ca","minutes_url":"https://www.northcowichan.ca/municipal-hall/mayor-council/agendas-minutes-video","scan_status":"pending"}
];

insertMunicipalities(municipalities);
