// This file will be auto-generated by Supabase CLI
// Run: npm run db:types
// For now, this is a placeholder with basic type structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          settings: Json;
          owner_id: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          settings?: Json;
          owner_id: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          settings?: Json;
          owner_id?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "projects_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      project_memberships: {
        Row: {
          id: string;
          project_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'member' | 'viewer';
          invited_by: string | null;
          invited_at: string | null;
          joined_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          user_id: string;
          role?: 'owner' | 'admin' | 'member' | 'viewer';
          invited_by?: string | null;
          invited_at?: string | null;
          joined_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          user_id?: string;
          role?: 'owner' | 'admin' | 'member' | 'viewer';
          invited_by?: string | null;
          invited_at?: string | null;
          joined_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "project_memberships_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "project_memberships_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      organizations: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          domain: string | null;
          website: string | null;
          industry: string | null;
          employee_count: number | null;
          annual_revenue: number | null;
          description: string | null;
          logo_url: string | null;
          linkedin_url: string | null;
          address_street: string | null;
          address_city: string | null;
          address_state: string | null;
          address_postal_code: string | null;
          address_country: string | null;
          phone: string | null;
          custom_fields: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          domain?: string | null;
          website?: string | null;
          industry?: string | null;
          employee_count?: number | null;
          annual_revenue?: number | null;
          description?: string | null;
          logo_url?: string | null;
          linkedin_url?: string | null;
          address_street?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_postal_code?: string | null;
          address_country?: string | null;
          phone?: string | null;
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          domain?: string | null;
          website?: string | null;
          industry?: string | null;
          employee_count?: number | null;
          annual_revenue?: number | null;
          description?: string | null;
          logo_url?: string | null;
          linkedin_url?: string | null;
          address_street?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_postal_code?: string | null;
          address_country?: string | null;
          phone?: string | null;
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "organizations_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          }
        ];
      };
      people: {
        Row: {
          id: string;
          project_id: string;
          first_name: string;
          last_name: string;
          email: string | null;
          phone: string | null;
          mobile_phone: string | null;
          job_title: string | null;
          department: string | null;
          linkedin_url: string | null;
          twitter_handle: string | null;
          avatar_url: string | null;
          timezone: string | null;
          preferred_contact_method: string | null;
          notes: string | null;
          address_street: string | null;
          address_city: string | null;
          address_state: string | null;
          address_postal_code: string | null;
          address_country: string | null;
          enrichment_status: string | null;
          enriched_at: string | null;
          enrichment_data: Json | null;
          custom_fields: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          project_id: string;
          first_name: string;
          last_name: string;
          email?: string | null;
          phone?: string | null;
          mobile_phone?: string | null;
          job_title?: string | null;
          department?: string | null;
          linkedin_url?: string | null;
          twitter_handle?: string | null;
          avatar_url?: string | null;
          timezone?: string | null;
          preferred_contact_method?: string | null;
          notes?: string | null;
          address_street?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_postal_code?: string | null;
          address_country?: string | null;
          enrichment_status?: string | null;
          enriched_at?: string | null;
          enrichment_data?: Json | null;
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          first_name?: string;
          last_name?: string;
          email?: string | null;
          phone?: string | null;
          mobile_phone?: string | null;
          job_title?: string | null;
          department?: string | null;
          linkedin_url?: string | null;
          twitter_handle?: string | null;
          avatar_url?: string | null;
          timezone?: string | null;
          preferred_contact_method?: string | null;
          notes?: string | null;
          address_street?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_postal_code?: string | null;
          address_country?: string | null;
          enrichment_status?: string | null;
          enriched_at?: string | null;
          enrichment_data?: Json | null;
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "people_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          }
        ];
      };
      opportunities: {
        Row: {
          id: string;
          project_id: string;
          name: string;
          description: string | null;
          stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost';
          amount: number | null;
          currency: string | null;
          probability: number | null;
          expected_close_date: string | null;
          actual_close_date: string | null;
          organization_id: string | null;
          primary_contact_id: string | null;
          owner_id: string | null;
          stage_changed_at: string | null;
          days_in_stage: number | null;
          lost_reason: string | null;
          won_reason: string | null;
          competitor: string | null;
          source: string | null;
          campaign: string | null;
          custom_fields: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          project_id: string;
          name: string;
          description?: string | null;
          stage?: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost';
          amount?: number | null;
          currency?: string | null;
          probability?: number | null;
          expected_close_date?: string | null;
          actual_close_date?: string | null;
          organization_id?: string | null;
          primary_contact_id?: string | null;
          owner_id?: string | null;
          stage_changed_at?: string | null;
          days_in_stage?: number | null;
          lost_reason?: string | null;
          won_reason?: string | null;
          competitor?: string | null;
          source?: string | null;
          campaign?: string | null;
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          name?: string;
          description?: string | null;
          stage?: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost';
          amount?: number | null;
          currency?: string | null;
          probability?: number | null;
          expected_close_date?: string | null;
          actual_close_date?: string | null;
          organization_id?: string | null;
          primary_contact_id?: string | null;
          owner_id?: string | null;
          stage_changed_at?: string | null;
          days_in_stage?: number | null;
          lost_reason?: string | null;
          won_reason?: string | null;
          competitor?: string | null;
          source?: string | null;
          campaign?: string | null;
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "opportunities_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          }
        ];
      };
      rfps: {
        Row: {
          id: string;
          project_id: string;
          title: string;
          description: string | null;
          status: 'identified' | 'reviewing' | 'preparing' | 'submitted' | 'won' | 'lost' | 'no_bid';
          rfp_number: string | null;
          organization_id: string | null;
          opportunity_id: string | null;
          owner_id: string | null;
          issue_date: string | null;
          due_date: string | null;
          questions_due_date: string | null;
          decision_date: string | null;
          estimated_value: number | null;
          currency: string | null;
          budget_range: string | null;
          submission_method: string | null;
          submission_portal_url: string | null;
          submission_email: string | null;
          submission_instructions: string | null;
          win_probability: number | null;
          go_no_go_decision: string | null;
          go_no_go_date: string | null;
          go_no_go_notes: string | null;
          outcome_reason: string | null;
          feedback: string | null;
          awarded_to: string | null;
          rfp_document_url: string | null;
          response_document_url: string | null;
          custom_fields: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          project_id: string;
          title: string;
          description?: string | null;
          status?: 'identified' | 'reviewing' | 'preparing' | 'submitted' | 'won' | 'lost' | 'no_bid';
          rfp_number?: string | null;
          organization_id?: string | null;
          opportunity_id?: string | null;
          owner_id?: string | null;
          issue_date?: string | null;
          due_date?: string | null;
          questions_due_date?: string | null;
          decision_date?: string | null;
          estimated_value?: number | null;
          currency?: string | null;
          budget_range?: string | null;
          submission_method?: string | null;
          submission_portal_url?: string | null;
          submission_email?: string | null;
          submission_instructions?: string | null;
          win_probability?: number | null;
          go_no_go_decision?: string | null;
          go_no_go_date?: string | null;
          go_no_go_notes?: string | null;
          outcome_reason?: string | null;
          feedback?: string | null;
          awarded_to?: string | null;
          rfp_document_url?: string | null;
          response_document_url?: string | null;
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          project_id?: string;
          title?: string;
          description?: string | null;
          status?: 'identified' | 'reviewing' | 'preparing' | 'submitted' | 'won' | 'lost' | 'no_bid';
          rfp_number?: string | null;
          organization_id?: string | null;
          opportunity_id?: string | null;
          owner_id?: string | null;
          issue_date?: string | null;
          due_date?: string | null;
          questions_due_date?: string | null;
          decision_date?: string | null;
          estimated_value?: number | null;
          currency?: string | null;
          budget_range?: string | null;
          submission_method?: string | null;
          submission_portal_url?: string | null;
          submission_email?: string | null;
          submission_instructions?: string | null;
          win_probability?: number | null;
          go_no_go_decision?: string | null;
          go_no_go_date?: string | null;
          go_no_go_notes?: string | null;
          outcome_reason?: string | null;
          feedback?: string | null;
          awarded_to?: string | null;
          rfp_document_url?: string | null;
          response_document_url?: string | null;
          custom_fields?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "rfps_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          }
        ];
      };
      custom_field_definitions: {
        Row: {
          id: string;
          project_id: string;
          entity_type: 'organization' | 'person' | 'opportunity' | 'rfp';
          name: string;
          label: string;
          description: string | null;
          field_type: 'text' | 'textarea' | 'number' | 'currency' | 'percentage' | 'date' | 'datetime' | 'boolean' | 'select' | 'multi_select' | 'url' | 'email' | 'phone' | 'rating' | 'user';
          is_required: boolean;
          is_unique: boolean;
          is_searchable: boolean;
          is_filterable: boolean;
          is_visible_in_list: boolean;
          display_order: number;
          group_name: string | null;
          options: Json;
          default_value: Json | null;
          validation_rules: Json | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          entity_type: 'organization' | 'person' | 'opportunity' | 'rfp';
          name: string;
          label: string;
          description?: string | null;
          field_type: 'text' | 'textarea' | 'number' | 'currency' | 'percentage' | 'date' | 'datetime' | 'boolean' | 'select' | 'multi_select' | 'url' | 'email' | 'phone' | 'rating' | 'user';
          is_required?: boolean;
          is_unique?: boolean;
          is_searchable?: boolean;
          is_filterable?: boolean;
          is_visible_in_list?: boolean;
          display_order?: number;
          group_name?: string | null;
          options?: Json;
          default_value?: Json | null;
          validation_rules?: Json | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          entity_type?: 'organization' | 'person' | 'opportunity' | 'rfp';
          name?: string;
          label?: string;
          description?: string | null;
          field_type?: 'text' | 'textarea' | 'number' | 'currency' | 'percentage' | 'date' | 'datetime' | 'boolean' | 'select' | 'multi_select' | 'url' | 'email' | 'phone' | 'rating' | 'user';
          is_required?: boolean;
          is_unique?: boolean;
          is_searchable?: boolean;
          is_filterable?: boolean;
          is_visible_in_list?: boolean;
          display_order?: number;
          group_name?: string | null;
          options?: Json;
          default_value?: Json | null;
          validation_rules?: Json | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "custom_field_definitions_project_id_fkey";
            columns: ["project_id"];
            isOneToOne: false;
            referencedRelation: "projects";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      entity_type: 'organization' | 'person' | 'opportunity' | 'rfp';
      field_type: 'text' | 'textarea' | 'number' | 'currency' | 'percentage' | 'date' | 'datetime' | 'boolean' | 'select' | 'multi_select' | 'url' | 'email' | 'phone' | 'rating' | 'user';
      opportunity_stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost';
      project_role: 'owner' | 'admin' | 'member' | 'viewer';
      rfp_status: 'identified' | 'reviewing' | 'preparing' | 'submitted' | 'won' | 'lost' | 'no_bid';
    };
  };
};
