import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { createServiceClient } from '@/lib/supabase/server';

interface CertificateOptions {
  documentId: string;
  projectId: string | null;
}

export async function generateCertificate(options: CertificateOptions): Promise<Uint8Array> {
  const { documentId } = options;
  const supabase = createServiceClient();

  // Get document info
  const { data: document } = await supabase
    .from('contract_documents')
    .select('title, original_file_name, original_file_hash, signed_file_hash, completed_at, sent_at, page_count')
    .eq('id', documentId)
    .single();

  if (!document) throw new Error('Document not found');

  // Get recipients
  const { data: recipients } = await supabase
    .from('contract_recipients')
    .select('name, email, role, status, signed_at, signing_ip, consent_timestamp, consent_ip')
    .eq('document_id', documentId)
    .eq('role', 'signer')
    .order('signing_order', { ascending: true });

  // Get audit trail
  const { data: auditTrail } = await supabase
    .from('contract_audit_trail')
    .select('action, actor_name, ip_address, created_at')
    .eq('document_id', documentId)
    .in('action', ['created', 'sent', 'signed', 'completed'])
    .order('created_at', { ascending: true });

  // Create PDF
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage([612, 792]); // Letter size
  let y = 740;

  const drawText = (text: string, opts: { x?: number; size?: number; bold?: boolean; color?: [number, number, number] } = {}) => {
    const { x = 50, size = 11, bold = false, color = [0, 0, 0] } = opts;
    // Add new page if running out of space
    if (y < 60) {
      page = pdfDoc.addPage([612, 792]);
      y = 740;
    }
    page.drawText(text, {
      x,
      y,
      size,
      font: bold ? boldFont : font,
      color: rgb(color[0], color[1], color[2]),
    });
    y -= size + 6;
  };

  // Header
  drawText('CERTIFICATE OF COMPLETION', { size: 18, bold: true, x: 150 });
  y -= 10;

  // Divider
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
  y -= 20;

  // Document info
  drawText('Document Details', { size: 14, bold: true });
  y -= 5;
  drawText(`Title: ${document.title}`);
  drawText(`File: ${document.original_file_name}`);
  drawText(`Pages: ${document.page_count}`);
  drawText(`Document ID: ${documentId}`);
  if (document.original_file_hash) {
    drawText(`Original SHA-256: ${document.original_file_hash}`);
  }
  if (document.signed_file_hash) {
    drawText(`Signed SHA-256: ${document.signed_file_hash}`);
  }

  y -= 15;
  drawText('Timeline', { size: 14, bold: true });
  y -= 5;

  if (document.sent_at) {
    drawText(`Sent: ${new Date(document.sent_at).toUTCString()}`);
  }
  if (document.completed_at) {
    drawText(`Completed: ${new Date(document.completed_at).toUTCString()}`);
  }

  y -= 15;
  drawText('Signers', { size: 14, bold: true });
  y -= 5;

  for (const r of recipients ?? []) {
    drawText(`${r.name} (${r.email})`, { bold: true });
    drawText(`  Status: ${r.status}`);
    if (r.consent_timestamp) {
      drawText(`  Consent: ${new Date(r.consent_timestamp).toUTCString()} from ${r.consent_ip ?? 'unknown'}`);
    }
    if (r.signed_at) {
      drawText(`  Signed: ${new Date(r.signed_at).toUTCString()} from ${r.signing_ip ?? 'unknown'}`);
    }
    y -= 5;
  }

  y -= 10;
  drawText('Audit Events', { size: 14, bold: true });
  y -= 5;

  for (const entry of auditTrail ?? []) {
    const time = new Date(entry.created_at).toUTCString();
    const actor = entry.actor_name ? ` by ${entry.actor_name}` : '';
    const ip = entry.ip_address ? ` (${entry.ip_address})` : '';
    drawText(`${time} - ${entry.action}${actor}${ip}`, { size: 9 });
  }

  y -= 20;
  page.drawLine({ start: { x: 50, y }, end: { x: 562, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
  y -= 15;

  drawText('This certificate was automatically generated by GoodRevCRM.', { size: 9, color: [0.5, 0.5, 0.5] });
  drawText(`Generated at: ${new Date().toUTCString()}`, { size: 9, color: [0.5, 0.5, 0.5] });

  return new Uint8Array(await pdfDoc.save());
}
