-- Migration 039: RFP Questions table
-- Break down RFPs into individual questions/requirements with answer tracking

CREATE TYPE public.rfp_question_status AS ENUM (
    'unanswered',
    'draft',
    'review',
    'approved'
);

CREATE TABLE IF NOT EXISTS public.rfp_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rfp_id UUID NOT NULL REFERENCES public.rfps(id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,

    -- Question content
    section_name TEXT,
    question_number TEXT,
    question_text TEXT NOT NULL,

    -- Answer content
    answer_text TEXT,
    answer_html TEXT,

    -- Status and workflow
    status public.rfp_question_status NOT NULL DEFAULT 'unanswered',
    priority TEXT CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    assigned_to UUID REFERENCES public.users(id) ON DELETE SET NULL,

    -- AI metadata
    ai_generated BOOLEAN NOT NULL DEFAULT false,
    ai_confidence DECIMAL(3,2) CHECK (ai_confidence >= 0 AND ai_confidence <= 1),
    content_library_source_id UUID,

    -- Ordering
    sort_order INTEGER NOT NULL DEFAULT 0,

    -- Notes
    notes TEXT,

    -- Metadata
    created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- Enable Row Level Security
ALTER TABLE public.rfp_questions ENABLE ROW LEVEL SECURITY;

-- Apply updated_at trigger
CREATE TRIGGER set_rfp_questions_updated_at
    BEFORE UPDATE ON public.rfp_questions
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_rfp_questions_rfp_id ON public.rfp_questions(rfp_id);
CREATE INDEX IF NOT EXISTS idx_rfp_questions_project_id ON public.rfp_questions(project_id);
CREATE INDEX IF NOT EXISTS idx_rfp_questions_status ON public.rfp_questions(status);
CREATE INDEX IF NOT EXISTS idx_rfp_questions_section ON public.rfp_questions(section_name);
CREATE INDEX IF NOT EXISTS idx_rfp_questions_assigned_to ON public.rfp_questions(assigned_to);
CREATE INDEX IF NOT EXISTS idx_rfp_questions_deleted_at ON public.rfp_questions(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_rfp_questions_sort ON public.rfp_questions(rfp_id, sort_order);

-- RLS Policies

CREATE POLICY "Members can view project rfp_questions"
    ON public.rfp_questions
    FOR SELECT
    USING (
        deleted_at IS NULL
        AND public.is_project_member(project_id)
    );

CREATE POLICY "Members can create rfp_questions"
    ON public.rfp_questions
    FOR INSERT
    WITH CHECK (
        public.has_project_role(project_id, 'member')
    );

CREATE POLICY "Members can update rfp_questions"
    ON public.rfp_questions
    FOR UPDATE
    USING (
        deleted_at IS NULL
        AND public.has_project_role(project_id, 'member')
    )
    WITH CHECK (
        public.has_project_role(project_id, 'member')
    );

CREATE POLICY "Members can delete rfp_questions"
    ON public.rfp_questions
    FOR DELETE
    USING (
        public.has_project_role(project_id, 'member')
    );

-- Comments
COMMENT ON TABLE public.rfp_questions IS 'Individual questions/requirements within an RFP';
COMMENT ON COLUMN public.rfp_questions.section_name IS 'Grouping section (e.g., Technical Requirements, Security)';
COMMENT ON COLUMN public.rfp_questions.question_number IS 'External question number (e.g., 3.2.1)';
COMMENT ON COLUMN public.rfp_questions.ai_generated IS 'Whether the answer was generated by AI';
COMMENT ON COLUMN public.rfp_questions.content_library_source_id IS 'FK to content library entry used as source (added in migration 0040)';
